### ISSUE TITLE
v4.0.1 breaks LLDB in Xcode

### ISSUE THREAD

**Issue by andyyhope** [twilio/conversations-ios#42]
We're using the latest version (`4.0.1`) via SPM and it has broken our ability to use LLDB. Upon further inspection, it appears that the included binary `twilio-conversations-ios-4.0.1.xcframework` is exporting absolute search paths for the `SDKStatCaches.noindex` directory. For example, when we try to `po` a variable, the following error is shown:

```
(lldb) po myString
error: expression failed to parse:
error: stat cache file '/Users/distiller/rtd-sdk-monorepo/sdk/ios/Local/temp/DerivedData/SDKStatCaches.noindex/iphonesimulator16.4-20E238-.sdkstatcache' not found
error: stat cache file '/Users/distiller/rtd-sdk-monorepo/sdk/ios/Local/temp/DerivedData/SDKStatCaches.noindex/iphonesimulator16.4-20E238-.sdkstatcache' not found

error: couldn't IRGen expression. Please check the above error messages for possible root causes.
```

## Possible solutions:
Update the project to include the following flag so absolute search paths aren't used:
```
OTHER_SWIFT_FLAGS = "-Xfrontend -no-serialize-debugging-options"
```

**Comment by mthormann-dhi** [comment]
Saw this as well. https://github.com/twilio/conversations-ios/issues/36 also but don't think anything was ever done on it. @andyyhope Did that workaround work for you w/o side effects?

**Comment by andyyhope** [comment]
I've actually tried a *bunch* of things to get a workaround on this:

# LLDB
Added an `LLDBinit` file to redirect the `distiller` path to a local one:
```
settings set target.source-map /Users/distiller/rtd-sdk-monorepo/sdk/ios/Local/temp/DerivedData/SDKStatCaches.noindex/iphonesimulator16.4-20E238-.sdkstatcache /Users/andyyhope/Library/Developer/Xcode/DerivedData/SDKStatCaches.noindex/iphonesimulator16.4-20E238-.sdkstatcache /Users/distiller/rtd-sdk-monorepo/sdk/ios/Local/temp/DerivedData/Build/Intermediates.noindex/ArchiveIntermediates/TwilioConversationsClient/IntermediateBuildFilesPath/TwilioConversationsClient.build/Release-iphonesimulator/TwilioConversationsClient.build/all-product-headers.yaml /Users/andyyhope/Downloads/TestTwilioLLDBWorkspace/TestTwilioLLDB/all-product-headers.yaml
```

# VFS Overlays
Added a VFS overlay to the swift compile flags
```bash
-Xcc -ivfsoverlay -Xcc vfsoverlay.yaml
```

```yaml
{
  'version': 0,
  'roots': [
    { 
      'name': '/Users/distiller/rtd-sdk-monorepo/sdk/ios/Local/temp/DerivedData/SDKStatCaches.noindex', 
      'type': 'directory',
      'contents': [
        { 
          'name': 'iphonesimulator16.4-20E238-.sdkstatcache', 
          'type': 'file',
          'external-contents': 'SDKStatCaches.noindex/iphonesimulator16.4-20E238-.sdkstatcache'
        },
      ]
    },
    { 
      'name': '/Users/distiller/rtd-sdk-monorepo/sdk/ios/Local/temp/DerivedData/Build/Intermediates.noindex/ArchiveIntermediates/TwilioConversationsClient/IntermediateBuildFilesPath/TwilioConversationsClient.build/Release-iphonesimulator/TwilioConversationsClient.build', 
      'type': 'directory',
      'contents': [
        { 
          'name': 'all-product-headers.yaml', 
          'type': 'file',
          'external-contents': 'all-product-headers.yaml'
        },
      ]
    },
  ]
}
```

# Added compiler flags
To redirect distiller paths to my own
```bash
-fdebug-prefix-map=/Users/distiller/rtd-sdk-monorepo/sdk/ios/Local/temp/DerivedData/SDKStatCaches.noindex=/Users/andyyhope/Downloads/TestTwilioLLDBWorkspace/TestTwilioLLDB/SDKStatCaches.noindex
```

# Modifying the `twilio-conversations-ios-4.0.1` binary
- Removed the references to dSYMs and dSYM files altogether 
- Modified the actual binary files to swap paths to `distiller` with my own
